### ISSUE TITLE
Banner H2 contrast with background colour

### ISSUE THREAD

**Issue by bensullivan8** [bensullivan8/arrrgenes-treasure-tours#1]
Hello again, @muxlowc. Last issue (hopefully).
This whole thing is starting to bug me and I'm sick of staring at it. Not really sure how to go about it at this point...
<img width="617" alt="Screen Shot 2020-04-20 at 10 49 02 PM" src="https://user-images.githubusercontent.com/55108838/79820123-82529680-8359-11ea-9a82-59d8af9e8a8e.png">
I still don't understand why black wouldn't work.

Thanks for all your help today by the way. A life-saver!

**Comment by muxlowc** [comment]
@bensullivan8 I think markbot wants the dark-green hex color, rather than black for the .banner

**Comment by bensullivan8** [comment]
Took a little longer than expected but eventually got it. Thanks @muxlowc
